server:
  port: 8893
eureka:
  instance:
    hostname: localhost
  client:
    #    disable client behavior
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8891/eureka/